DROP TABLE IF EXISTS TBL_EMPLOYEES;
DROP TABLE IF EXISTS TBL_SALES;
DROP TABLE IF EXISTS TBL_ORDER;
DROP TABLE IF EXISTS TBL_PRODUCT;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_SALES(
	Sale_id INT AUTO_INCREMENT  PRIMARY KEY,
	company VARCHAR(250) NOT NULL,
	order_id INT NOT NULL,
	quality INT NOT NULL,
	sale_price VARCHAR(250) NOT NULL,
	product_id INT NOT NULL,
	currency VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_ORDER(
	order_id INT AUTO_INCREMENT  PRIMARY KEY,
	order_number INT NOT NULL,
	company VARCHAR(250) NOT NULL,
	order_date VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_PRODUCT(
	product_id INT AUTO_INCREMENT  PRIMARY KEY,
	company_prodid INT NOT NULL,
	company_name VARCHAR(250) NOT NULL,
	product_name VARCHAR(250) NOT NULL,
	cost VARCHAR(250) NOT NULL,
	currency VARCHAR(250) NOT NULL
);